export { apiRequest, API_BASE } from "@/lib/api/client";
export { ApiError } from "@/lib/api/errors";
export {
  login,
  register,
  forgotPassword,
  resetPassword,
  logout,
} from "@/lib/api/auth";
export {
  getProfile,
  getProfileDashboard,
  updateProfile,
  changePassword,
  uploadAvatar,
  getProfileStats,
  getProfileSettings,
  updateProfileSettings,
  getProfileActivity,
  getProfileSessions,
  terminateSession,
  updateTwoFactor,
  deleteProfile,
} from "@/lib/api/profile";
export { getCourse, getCourseFilters, getCourses } from "@/lib/api/courses";
export { createApplication, getMyApplications } from "@/lib/api/applications";
export {
  createEmployee,
  deleteEmployee,
  getEmployees,
  getManagementClient,
  getManagementClients,
  getManagementReports,
  updateEmployeeRole,
} from "@/lib/api/admin-management";
export {
  decideApplication,
  getClientAppeals,
  getClientApplications,
  getClientCourseProgress,
  getSupervisorApplications,
  getSupervisorClient,
  getSupervisorClients,
  updateClientStatus,
  updateSupervisorClientPassword,
} from "@/lib/api/admin-supervisor";
export {
  createItCourse,
  createItCourseModule,
  createItDirection,
  createItLesson,
  createItLessonAssignment,
  createItLessonMaterial,
  createItModule,
  createItModuleMaterial,
  deleteItAssignment,
  deleteItCourse,
  deleteItDirection,
  deleteItLesson,
  deleteItMaterial,
  deleteItModule,
  getItCategories,
  getItCourse,
  getItCourses,
  getItCoursesPage,
  getItDirection,
  getItDirections,
  getItDirectionsPage,
  getItSettings,
  getSystemHealth,
  updateItAssignment,
  updateItCourse,
  updateItDirection,
  updateItLesson,
  updateItMaterial,
  updateItModule,
  updateItSetting,
  updateItUserRole,
} from "@/lib/api/admin-it";
export {
  completeLearningLesson,
  enrollInCourse,
  getLearningCourse,
  getLearningLesson,
  getMyLearningCourses,
} from "@/lib/api/learning";
export {
  applyNotificationMutation,
  createNotification,
  deleteNotification,
  deleteAllNotifications,
  getNotifications,
  getUnreadCount,
  markAllNotificationsRead,
  markNotificationRead,
  sendNotificationToAdmin,
} from "@/lib/api/notifications";
export {
  createQualificationDirection,
  createQualificationLesson,
  createQualificationModule,
  deleteQualificationDirection,
  deleteQualificationLesson,
  deleteQualificationMaterial,
  deleteQualificationModule,
  deleteQualificationTest,
  getQualificationDirection,
  getQualificationDirections,
  publishLesson,
  saveLessonDraft,
  setLessonStatus,
  setModuleStatus,
  submitLessonMaterial,
  updateQualificationDirection,
  updateQualificationLesson,
  updateQualificationModule,
  uploadLessonMaterial,
} from "@/lib/api/qualification";
export {
  createAdminLibraryItem,
  deleteAdminLibraryItem,
  getAdminLibrary,
  getAdminLibraryItem,
  setAdminLibraryStatus,
  updateAdminLibraryItem,
  uploadLibraryFile,
} from "@/lib/api/library";
export { getStudentLibrary, getStudentLibraryItem } from "@/lib/api/library-student";
export type { LibraryItem, LibraryListQuery, LibraryWritePayload } from "@/lib/api/types/library";
export {
  createMandatoryBlog,
  createMandatoryLesson,
  createMandatoryModule,
  deleteMandatoryBlog,
  deleteMandatoryLesson,
  deleteMandatoryMaterial,
  deleteMandatoryModule,
  getMandatoryBlog,
  getMandatoryBlogModules,
  getMandatoryBlogs,
  getMandatoryBlogsDetailed,
  getMandatoryLessonMaterials,
  getMandatoryModuleLessons,
  publishMandatoryLesson,
  saveMandatoryLessonDraft,
  setMandatoryLessonStatus,
  setMandatoryModuleStatus,
  submitMandatoryLessonMaterial,
  updateMandatoryBlog,
  updateMandatoryLesson,
  updateMandatoryMaterial,
  updateMandatoryModule,
} from "@/lib/api/mandatory-blogs";
export type {
  AuthResponse,
  ForgotPasswordRequest,
  LoginRequest,
  MessageResponse,
  RegisterRequest,
  ResetPasswordRequest,
  UserResponse,
} from "@/lib/api/types/auth";
export type {
  ActivityResponse,
  ChangePasswordRequest,
  ProfileDashboardResponse,
  ProfileResponse,
  ProfileStatsResponse,
  SecurityResponse,
  SessionResponse,
  SettingsResponse,
  UpdateProfileRequest,
  UpdateSettingsRequest,
  UpdateTwoFactorRequest,
} from "@/lib/api/types/profile";
export type {
  CourseCardResponse,
  CourseDetailResponse,
  CourseFiltersResponse,
  CourseListQuery,
  CourseListResponse,
  CourseModuleResponse,
  FilterOption,
} from "@/lib/api/types/courses";
export type {
  LearningAssignment,
  LearningCourseResponse,
  LearningLessonDetail,
  LearningLessonSummary,
  LearningMaterial,
  LearningModule,
  LessonItemType,
  MaterialType,
} from "@/lib/api/types/learning";
export type {
  CreateQualificationDirectionPayload,
  CreateQualificationLessonPayload,
  CreateQualificationModulePayload,
  QualificationDirection,
  QualificationLesson,
  QualificationLessonType,
  QualificationMaterialType,
  QualificationModule,
} from "@/lib/api/types/qualification";
