export const dashboardLabels = {
  platformTagline: "Malaka oshirish platformasi",
  roleBadge: "Pedagog",
  logout: "Chiqish",
  search: "Qidirish...",
  searchCourses: "Kurs nomi yoki yo'nalish bo'yicha qidiring...",
  save: "Saqlash",
  cancel: "Bekor qilish",
  close: "Yopish",
  view: "Ko'rish",
  download: "Yuklab olish",
  details: "Batafsil",
  continueLearning: "O'qishni davom ettirish",
  startLearning: "O'qishni boshlash",
  applyCourse: "Kursga ariza topshirish",
  applied: "Ariza yuborilgan",
  viewResult: "Natijani ko'rish",
  startTest: "Testni boshlash",
  finishTest: "Testni yakunlash",
  markRead: "O'qildi deb belgilash",
  markAllRead: "Barchasini o'qilgan qilish",
  editPortfolio: "Portfolio tahrirlash",
  noData: "Ma'lumot topilmadi",
  loading: "Yuklanmoqda...",
  confirm: "Tasdiqlash",
  previous: "Oldingi",
  next: "Keyingi",
  markQuestion: "Belgilab qo'yish",
  all: "Barchasi",
  active: "Faol",
  completed: "Tugallangan",
  pending: "Kutilmoqda",
  profile: "Profil",
  settings: "Sozlamalar",
  menu: {
    home: "Bosh sahifa",
    courses: "Malaka oshirish yo'nalishi",
    courseAbout: "Kurs haqida",
    myCourses: "Mening yo'nalishim",
    applications: "Arizalarim",
    learning: "O'quv jarayoni (Darslar)",
    results: "Natijalarim",
    portfolio: "Portfolio",
    notifications: "Bildirishnomalar",
    profile: "Profil",
  },
  pages: {
    dashboard: "Bosh sahifa",
    courses: "Malaka oshirish yo'nalishi",
    courseDetail: "Kurs haqida",
    myCourses: "Mening yo'nalishim",
    applications: "Arizalarim",
    learning: "O'quv jarayoni",
    results: "Natijalarim",
    portfolio: "Portfolio",
    notifications: "Bildirishnomalar",
    profile: "Profil",
  },
  status: {
    reviewing: "Ko'rib chiqilmoqda",
    approved: "Tasdiqlandi",
    rejected: "Rad etildi",
    payment_pending: "To'lov kutilmoqda",
    activated: "Faollashtirildi",
    success: "Muvaffaqiyatli",
    satisfactory: "Qoniqarli",
    retry: "Qayta topshirish",
    available: "Mavjud",
    passed: "O'tilgan",
    failed: "O'tilmagan",
    in_progress: "Jarayonda",
  },
} as const;

export type DashboardPageKey = keyof typeof dashboardLabels.pages;
